# Generated by Django 3.1 on 2020-11-08 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_responsibility',
            field=models.TextField(default=django.utils.timezone.now, max_length=1024, verbose_name='职位职责'),
            preserve_default=False,
        ),
    ]
